"use client";
import {useEffect,useState} from "react";
import {api,type Session} from "@/lib/api";
import {Shell} from "./tutoria";
type Account={id:string;username:string;name:string;role:string;must_change:number};
export default function AdminPanel({session}:{session:Session}){
 const [accounts,setAccounts]=useState<Account[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[name,setName]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[reset,setReset]=useState<Account|null>(null),[remove,setRemove]=useState<Account|null>(null);
 const load=async()=>setAccounts((await api<{accounts:Account[]}>("/api/admin/accounts")).accounts);
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");setNotice("");try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Shell active="teacher"><div className="dashboard-heading"><div><div className="eyebrow">DIGITAL TECHNOLOGIES</div><h1>Account administration</h1><p>Create teacher accounts and manage access to the learning hub.</p></div></div>
 {error&&<p role="alert" className="status error">{error}</p>}{notice&&<p role="status" className="status">{notice}</p>}
 <form className="editor-form exchange-stage" onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/api/admin/accounts',{name,username,password});setName('');setUsername('');setPassword('');setNotice('Teacher created. They must replace their temporary password at first login.');});}}><h2>Add a teacher</h2><div className="two-fields"><label>Full name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Username<input required pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{2,59}" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off"/></label></div><label>Temporary password — at least 12 characters<input required type="password" minLength={12} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><button disabled={busy} className="primary">Create teacher account</button></form>
 <h2>Accounts</h2><div className="account-list">{accounts.map(a=><div className="exchange-stage" key={a.id}><h3>{a.name}</h3><p>{a.username} · {a.role}{a.must_change?' · Password change required':''}</p><div className="editor-actions"><button disabled={busy} className="secondary" onClick={()=>{setReset(a);setPassword('');setRemove(null);}}>Reset password</button>{a.id!==session.user.id&&<button disabled={busy} className="secondary" onClick={()=>{setRemove(a);setReset(null);}}>Delete account</button>}</div></div>)}</div>
 {reset&&<form className="editor-form exchange-stage" onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/api/admin/password?id='+encodeURIComponent(reset.id),{password});if(reset.id===session.user.id){window.location.href='/teacher/login/';return;}setReset(null);setPassword('');setNotice('Password reset. Existing sessions have been signed out.');});}}><h2>Reset password for {reset.name}</h2><p>This signs the account out on all devices. They must choose a new password after signing in.</p><label>New temporary password<input type="password" required minLength={12} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><div className="editor-actions"><button disabled={busy} className="primary">Reset password</button><button type="button" className="secondary" onClick={()=>{setReset(null);setPassword('');}}>Cancel</button></div></form>}
 {remove&&<section className="exchange-stage"><h2>Delete {remove.name}'s account?</h2><p>This removes their login access, folders and lessons from the hub, including published lessons. There is no restore button. Their username will remain reserved.</p><div className="editor-actions"><button disabled={busy} className="primary" onClick={()=>void run(async()=>{await api('/api/admin/account?id='+encodeURIComponent(remove.id),{},'DELETE');setRemove(null);setNotice('Account removed and its lessons withdrawn.');})}>Delete account and withdraw lessons</button><button className="secondary" onClick={()=>setRemove(null)}>Cancel</button></div></section>}
 </Shell>;
}
